CHANGELOG
=========

# 2.8.1 / 2024-04-05

* [BUGFIX] Fix `import name 'cli' from '__main__' error [#70][] (Thanks [@tcaddy][])

# 2.8.0 / 2022-04-05

* [BUGFIX] Replace @ in events to avoid triggering notifications [#68][]
* [IMPROVEMENT] Provide better message on import errors to ease debugging [#65][]
* [IMPROVEMENT] Add requirements.txt file [#64][]

# 2.7.0 / 2021-05-10

* [IMPROVEMENT] Explain Ansible/Datadog hostname mismatch, allow overriding hostname. See [#60][]

# 2.6.0 / 2020-11-25
* [BUGFIX] Cast api_key as string in datadog.initialize [#54][]
* [BUGFIX] Add hook to handle incompatibilities between Ansible 2.7 and 2.8 [#47][] (Thanks [@rsdcobalt][])

# 2.5.1 / 2019-05-17
* [IMPROVEMENT] Use PyYaml's "FullLoader" to avoid unsafe load. See [#45][] (thanks to [@brandonshough][])

# 2.5.0 / 2019-02-07
* [FEATURE] Add support for "site" configuration.

# 2.4.2 / 2018-06-08
- [BUGFIX] Fix yaml import broken by Ansible 2.5.

# 2.4.1 / 2018-02-07
- [BUGFIX] Avoid printing error about the conf file when using a vault. See [#34][]

# 2.4.0 / 2018-02-07
- [FEATURE] Add support of python3 (and still fully support python2). See [#33][] (thanks to [@DSpeichert][])

# 2.3.0 / 2018-01-12
- [FEATURE] Don't send event about error when "ignore_errors" is True. See [#30][]

# 2.2.0 / 2017-12-27
- [FEATURE] Set log level to warning for the datadog and request packages. See [#24][] (thanks to [@n0ts][])
- [FEATURE] Allow users to set a custom location for the configuration file.
- [FEATURE] Added environment variables for configuring datadog api key. See [#22][] (thanks to [@pyconsult][])

# 2.1.0 / 2017-12-26
- [FEATURE] Disable callback if required python packages aren't installed. See [#28][] (thanks to [@dobber][])

# 2.0.0 / 2017-12-12
- [FEATURE] Add support for getting api_key from hostvars and thus from vault. See [#25][]
- [BREAKING CHANGE] Drop support for ansible <2.0

# 1.0.2 / 2017-12-11
* [BUGFIX] Avoid failure when using ansible 2.4. See [#27][]

# 1.0.1 / 2016-06-06
* [BUGFIX] Avoid failure when `res['invocation']` has no `module_name` key. See [#19][]

# 1.0.0 / 2016-06-02
First release, compatible with Ansible v1 & v2

<!--- The following link definition list is generated by PimpMyChangelog --->
[#19]: https://github.com/DataDog/ansible-datadog-callback/issues/19
[#22]: https://github.com/DataDog/ansible-datadog-callback/issues/22
[#24]: https://github.com/DataDog/ansible-datadog-callback/issues/24
[#25]: https://github.com/DataDog/ansible-datadog-callback/issues/25
[#27]: https://github.com/DataDog/ansible-datadog-callback/issues/27
[#28]: https://github.com/DataDog/ansible-datadog-callback/issues/28
[#30]: https://github.com/DataDog/ansible-datadog-callback/issues/30
[#33]: https://github.com/DataDog/ansible-datadog-callback/issues/33
[#34]: https://github.com/DataDog/ansible-datadog-callback/issues/34
[#45]: https://github.com/DataDog/ansible-datadog-callback/issues/45
[#47]: https://github.com/DataDog/ansible-datadog-callback/issues/47
[#54]: https://github.com/DataDog/ansible-datadog-callback/issues/54
[#60]: https://github.com/DataDog/ansible-datadog-callback/issues/60
[#64]: https://github.com/DataDog/ansible-datadog-callback/issues/64
[#65]: https://github.com/DataDog/ansible-datadog-callback/issues/65
[#68]: https://github.com/DataDog/ansible-datadog-callback/issues/68
[#70]: https://github.com/DataDog/ansible-datadog-callback/issues/70
[@DSpeichert]: https://github.com/DSpeichert
[@brandonshough]: https://github.com/brandonshough
[@dobber]: https://github.com/dobber
[@n0ts]: https://github.com/n0ts
[@pyconsult]: https://github.com/pyconsult
[@rsdcobalt]: https://github.com/rsdcobalt
[@tcaddy]: https://github.com/tcaddy